### ISSUE TITLE
1.0.0 Feature-completeness tracker

### ISSUE THREAD

**Issue by drdeaton** [whooprobotics/ReveilLib#1]
1.0.0 will be feature-complete and ready for pre-releases when creation, implementation, verification, debug, and documentation are ready for the following features:

- [ ] Motion
  - [ ] Simple motion (Verification/debug)
  - [ ] Proportional motion (Verification/debug)
  - [ ] Cascading motion (Verification/debug)
- [ ] Correction
  - [ ] Pilons Correction (Verification/debug)
- [ ] Odometry
  - [ ] Two Encoder+Gyro Odometry (Verification/debug)
  - [ ] Odometry update controller (Verification/debug)
- [ ] Units (Verification/debug)
- [ ] Reckless controller (Planning)

**Comment by drdeaton** [comment]
This will no longer be tracked here because the Aggie Robotics Software trello board exists now, but I will keep the issue open until its all done.

**Comment by drdeaton** [comment]
1.0.0 should be feature-complete
