### ISSUE TITLE
2.0.0 Feature Tracker

### ISSUE THREAD

**Issue by drdeaton** [whooprobotics/ReveilLib#23]
- [ ] Reckless Improvements
  - [x] User definable segment types supporting driving and other stuff (#22)
  - [x] Reckless turn segment
  - [ ] Bezier curve segment
  - [ ] Drive-to-pose segment
  - [x] Improve API for writing paths
  - [ ] Improve docs for using Reckless
- [ ] Controller API
